name: Label Issues

on:
  issues:
    types: [opened]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add labels based on template
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const labels = issue.title.includes("[FEATURE]") ? ['feature'] : ['bug'];
            const result = await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              labels: ['to be approved', ...labels]
            });
            console.log(result);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
